aws_region        = "us-east-1"
aws_access_key    = "AKIAVQP4YBXO7VI6LOUA"
aws_secret_key    = "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"

name = "infraestructura-eks"
eks_version = "1.21"
desired_size = "1"
max_size = "2"
min_size = "2"
instance_types = "t2.large"
force_update_version = "false"
disk_size = "30"
ami_type = "AL2_x86_64"
endpoint_private_access = "false"
endpoint_public_access = "true"

